### ISSUE TITLE
Change dashing -> foxy in rosdep command line

### ISSUE THREAD

**Issue by yjkim046** [lge-ros2/cloisim_ros#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hyunseok-yang** [comment]
It looks revised in README.md file 
right?
will close the issue.
thank you.

**Comment by hyunseok-yang** [comment]
### Runnig container for rviz2

Install nvidia-docker2 following the [guideline](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installing-on-ubuntu-and-debian)

```shell
xhost +

```
