### ISSUE TITLE
Error occur when making docker image

### ISSUE THREAD

**Issue by whjeong** [lge-ros2/cloisim_ros#12]
I'm trying to build docker image cloisim_ros. however, when I ran docker built, compile error occur at 'imageStarting >>> cloisim_ros_bringup'. Detail error is like below.

Step 8/10 : RUN ["/bin/bash", "-c", "source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build --symlink-install"]
 ---> Running in 1c6148594024
Starting >>> cloisim_ros_bridge_zmq
Starting >>> cloisim_ros_protobuf_msgs
Starting >>> elevator_system_msgs
Starting >>> realsense_adaptor_msgs
Finished <<< cloisim_ros_bridge_zmq [4.13s]
Finished <<< cloisim_ros_protobuf_msgs [10.4s]
Starting >>> cloisim_ros_base
Finished <<< realsense_adaptor_msgs [14.1s]
Finished <<< elevator_system_msgs [19.2s]
Finished <<< cloisim_ros_base [8.90s]
Starting >>> cloisim_ros_camera
Starting >>> cloisim_ros_elevatorsystem
Starting >>> cloisim_ros_gps
Starting >>> cloisim_ros_lidar
Starting >>> cloisim_ros_micom
Starting >>> cloisim_ros_multicamera
Starting >>> cloisim_ros_realsense
Starting >>> cloisim_ros_world
Finished <<< cloisim_ros_camera [14.5s]
Starting >>> cloisim_ros_depthcamera
Finished <<< cloisim_ros_world [15.2s]
Finished <<< cloisim_ros_multicamera [15.3s]
Finished <<< cloisim_ros_gps [15.6s]
Finished <<< cloisim_ros_lidar [15.8s]
Finished <<< cloisim_ros_realsense [15.8s]
Finished <<< cloisim_ros_elevatorsystem [16.8s]
Finished <<< cloisim_ros_micom [22.3s]
Finished <<< cloisim_ros_depthcamera [8.86s]
Starting >>> cloisim_ros_bringup
--- stderr: cloisim_ros_bringup
In file included from /usr/include/websocketpp/transport/asio/base.hpp:31,
                 from /usr/include/websocketpp/transport/asio/connection.hpp:31,
                 from /usr/include/websocketpp/transport/asio/endpoint.hpp:32,
                 from /usr/include/websocketpp/config/asio_no_tls_client.hpp:32,
                 from /opt/lge-ros2/src/cloisim_ros/cloisim_ros_bringup/include/cloisim_ros_bringup/websocket_service.hpp:18,
                 from /opt/lge-ros2/src/cloisim_ros/cloisim_ros_bringup/src/websocket_service.cpp:15:
/usr/include/websocketpp/common/asio.hpp:56:14: fatal error: boost/version.hpp: No such file or directory
   56 |     #include <boost/version.hpp>
      |              ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/cloisim_ros_bringup.dir/build.make:63: CMakeFiles/cloisim_ros_bringup.dir/src/websocket_service.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/websocketpp/transport/asio/base.hpp:31,
                 from /usr/include/websocketpp/transport/asio/connection.hpp:31,
                 from /usr/include/websocketpp/transport/asio/endpoint.hpp:32,
                 from /usr/include/websocketpp/config/asio_no_tls_client.hpp:32,
                 from /opt/lge-ros2/src/cloisim_ros/cloisim_ros_bringup/include/cloisim_ros_bringup/websocket_service.hpp:18,
                 from /opt/lge-ros2/src/cloisim_ros/cloisim_ros_bringup/src/main.cpp:26:
/usr/include/websocketpp/common/asio.hpp:56:14: fatal error: boost/version.hpp: No such file or directory
   56 |     #include <boost/version.hpp>
      |              ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/cloisim_ros_bringup.dir/build.make:76: CMakeFiles/cloisim_ros_bringup.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/cloisim_ros_bringup.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< cloisim_ros_bringup [3.46s, exited with code 2]

Summary: 14 packages finished [46.5s]
  1 package failed: cloisim_ros_bringup
  1 package had stderr output: cloisim_ros_bringup
The command '/bin/bash -c source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build --symlink-install' returned a non-zero code: 2

**Comment by hyunseok-yang** [comment]
Thanks for report!

There was missing depandancy library(asio) for websocketpp library in bringup package.

it would be OK with latest code in foxy branch
